# Cross-compilation configuration
# https://github.com/cross-rs/cross

[build.env]
passthrough = ["RUST_BACKTRACE"]

[target.aarch64-unknown-linux-gnu]
dockerfile = "docker/Dockerfile.aarch64"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "docker/Dockerfile.armhf"

[target.riscv64gc-unknown-linux-gnu]
dockerfile = "docker/Dockerfile.riscv64"

[target.x86_64-unknown-linux-gnu]
dockerfile = "docker/Dockerfile.x86_64"

[target.x86_64-unknown-linux-musl]
dockerfile = "docker/Dockerfile.x86_64-musl"

[target.aarch64-unknown-linux-musl]
dockerfile = "docker/Dockerfile.aarch64-musl"
